### ISSUE TITLE
Replacement for images as static icons

### ISSUE THREAD

**Issue by shreyassranganatha** [Vikram-Hegde/Tasker#2]
Try replacing your tick box icons into CSS scripts, provides simple transition into different websites, reduces site load speeds, better's animation, merges better with displays

**Comment by Vikram-Hegde** [comment]
@shreyassranganatha I am using SVG for the icon tick box to get a desired animation from it, I don't know whether CSS scripts allow me to do the same. If so please let me know. Thanks for the feedback.

**Comment by shreyassranganatha** [comment]
1. As long as you're not using dark/light themes on the same site, you can use Canvas to draw the "tick mark," and then style the canvas box to use a 50% border radius or anything specific, for the tick boxes... this can allow you to make more fun animations
2. A primary reason I opened this issue was because the icons were clearly visible to be images that didn't blend well with it's surroundings, you should consider drawing ticks on canvas to enable animations like the tick mark drawing itself etc
3. You could as well only use the tick mark for an icon and the background of a div, that'd give you a little more compatibility with the rest of the design specs

**Comment by Vikram-Hegde** [comment]
@shreyassranganatha 
- Dark/light theme on the site and canvas are not related. Themes can be solely achieved with class toggling using css and js.
- Second: the icons are **SVG** (Scalable Vector Graphics). It is more inituitive to animate a SVG rather than making a canvas. for a sole purpose of animating a tick mark. And SVG does a good job at it. Also SVG is a vector therefore it'll never pixalate, whereas that's not the case in canvas.
- And having a background with the tick mark is from UX perspective, to show that the completed task appears different than the rest of incomplete task.

**Comment by shreyassranganatha** [comment]
- you'll need to have to redraw the canvas every time the themes change, canvas is static that way, it stays off it's styles, that's how they're related
- The SVG part of your argument are fair, sorry
- The compatibility of the design was actually an extension of my previous point, the issue was with the png file I now suppose

**Comment by Vikram-Hegde** [comment]
- For which part of the app are you suggesting to use canvas now ?
- You don't have to apologize 😄, you and I are learners.
- Actually in the code, i'm nowhere using the png file. The one png file which is there in the repo consists of the design i'm targeting to code.

**Comment by shreyassranganatha** [comment]
I'm sorry, I am working on a few other projects, I can't contribute as of now, but let me know if you need something?
